parameters:
    web_path: %kernel.root_dir%/../web
    upload_path: uploads

club_user:
    default_country: DE
    #welcome_mail_attachments:
        #- shared/safe_image.png

club_account_economic:
    enabled: false
    agreement: xxxxxx
    username: %club_account_economic.username%
    password: %club_account_economic.password%
    economic_url: https://www.e-conomic.com/secure/api1/EconomicWebservice.asmx?WSDL
    contraAccount: 5820
    cashbook: Daglig
    currency: DKK

club_payment_cash:
    enabled: true
    controller: club_payment_cash_cash_index

club_payment_quickpay:
    enabled: false
    controller: club_payment_quickpay_quickpay_index
    merchant: 89898978
    secret: %club_payment_quickpay.secret%
    protocol: 7
    language: de
    currency: EUR
    autocapture: 1
#    allow_subscription: true
    #cardtypelock:
    autofee: 0
    quickpay_url: https://secure.quickpay.dk/
    testmode: 1

club_api:
    api_key: THIS_IS_A_DEMO_KEY

club_event:
    enabled: true

club_match:
    enabled: true

club_ranking:
    enabled: true
    ranking_top: 5

club_shop:
    view_shop: true
    hide_categories: false
    coupon_account_number: 1010
    guest_account_number: 1010
    voucher_text: Payment from %s, order %s

club_team:
    enabled: true
    future_occurs: 14
    minutes_before_schedule: 120
    minutes_after_schedule: 5
    penalty_enabled: true
    cancel_minute_before: 120
    cancel_minute_created: 5
    num_team_day: 1
    num_team_future: 4
    penalty_product_name: 'Penalty for missed team'
    public_user_activity: true
    #public_teamlist: true

club_booking:
    enabled: true
    enable_guest: true
    guest_price: 50
    num_book_guest_day: 2
    num_book_guest_future: 2
    num_book_same_partner_day: 2
    num_book_same_partner_future: 2
    num_book_day: 2
    num_book_future: 2
    days_book_future: 6
    days_book_future_entire_day: true
    cancel_minute_before: 120
    cancel_minute_created: 5
    cancel_without_checkin: false
    confirm_minutes_before: 120
    confirm_minutes_after: 5
    public_user_activity: true

club_mail:
    default_sender_address: info@clubmaster.org
    default_sender_name: ClubMaster Administrator
    mail_on_welcome: true
    mail_on_booking: true
    mail_on_order: true
    mail_on_order_confirm: true

club_feedback:
    enabled: true

club_exchange:
    enabled: true

club_welcome:
    #enable_blog: true

club_news:
    enabled: true

club_checkin:
    allowed_ip:
        - 127.0.0.1
        - ::1

club_weather:
    enabled: true
    appid: 2f57a52e713c92e62195a21efe934c0f
    location: Hamburg, DE
    #lonlat: 9.918700,57.048000
    #cityid: 2624886 # http://openweathermap.org/help/city_list.txt
    #units: metric

club_media:
    enabled: true

club_tournament:
    enabled: true

club_form_extra:
    #title: ClubMaster

club_extra:
    #facebook: true
    #twitter: true
    #googleplus: true

club_kiosk:
    default_location: 1
    jquery_theme: start
